// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Block struct {
	ID       string `json:"id"`
	Contents string `json:"contents"`
}

type BlockInput struct {
	ID       *string `json:"id"`
	Contents string  `json:"contents"`
}

type LoginInput struct {
	Name     *string `json:"name"`
	Password *string `json:"password"`
}

type Token struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type User struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	IsAdmin bool   `json:"isAdmin"`
}

type UserInput struct {
	ID       *string `json:"id"`
	Name     string  `json:"name"`
	Password string  `json:"password"`
	IsAdmin  bool    `json:"isAdmin"`
}
