// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Block struct {
	ID       string `json:"id"`
	Contents string `json:"contents"`
}

type BlockInput struct {
	ID       *string `json:"id"`
	Contents string  `json:"contents"`
}

type Token struct {
	Token     string `json:"token"`
	ExpiresAt *int   `json:"expires_at"`
}

type User struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	IsAdmin bool   `json:"isAdmin"`
}

type UserInput struct {
	ID      *string `json:"id"`
	Name    string  `json:"name"`
	IsAdmin bool    `json:"isAdmin"`
}
